# Python package

# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:



- task: ksmazpipelinetask@0
  name: setKsmSecretsStep
  inputs:
    keepersecretconfig: $(sm-config)
    secrets: |
      6ya_fdc6XTsZ7i7x9Jcodg/field/password > var:var_password
      6ya_fdc6XTsZ7i7x9Jcodg/field/password > out_password2
      6ya_fdc6XTsZ7i7x9Jcodg/field/password > out:out_password
      6ya_fdc6XTsZ7i7x9Jcodg/file/build-vsix.sh > file:/tmp/build-vsix.sh

- bash: echo $(var_password)
  name: "GOOD_Format_var_password"

- bash: echo $(setKsmSecretsStep.out_password)
  name: "GOOD_Format_out_out_password"

- bash: echo $(setKsmSecretsStep.out_password2)
  name: "GOOD_Format_out_password2"

- bash: echo $SECRET_KSMAZPIPELINETASK_OUT:OUT_PASSWORD
  name: "Format_env_variable_out_password"
  env:
    MY_MAPPED_ENV_VAR_PASSWORD: $(var_password) # the recommended way to map to an env variable


- script: |
    ls -la /tmp/build-vsix.sh
  name: "Show_Secret_File"


# - bash: |
#     echo "Using an input-macro works: $(mySecret)"
#     echo "Using the env var directly does not work: $MYSECRET"
#     echo "Using a global secret var mapped in the pipeline does not work either: $GLOBAL_MYSECRET"
#     echo "Using a global non-secret var mapped in the pipeline works: $GLOBAL_MY_MAPPED_ENV_VAR" 
#     echo "Using the mapped env var for this task works and is recommended: $MY_MAPPED_ENV_VAR"
#   env:
#     MY_MAPPED_ENV_VAR: $(mySecret) # the recommended way to map to an env variable

