# Python package

# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '$(python.version)'
#   displayName: 'Use Python $(python.version)'




- task: ksmazpipelinehello1@0
  inputs:
    keepersecretconfig: '{"hostname": "keepersecurity.com","clientId": "mfalTSKV7QVCQDktBbvrOp0S4yv4sCc/2SzXvFOmHToX9SbU0QP6xghYqWHH/+OxcmdmOPt9djWhUKDUErir0A==","privateKey": "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgcIYxpnv4ag6HrY2rz0LZX3NDoG5MqUdfOw/MT69mvSChRANCAASoBOc98NsIblxelVcuLv1X4/YF1muKKlfnBGnN/9SXdm1clXWp5Ie52kFMVSjzvkdAwhkqhM9YTAbBPsZ6urfG","serverPublicKeyId": "10","appKey": "F/s578hXvINYwEKasFzq54hL/U7tFxKooqMrshfT3ZA="}'
    secrets: |
      6ya_fdc6XTsZ7i7x9Jcodg/field/password > env:pazzword
      6ya_fdc6XTsZ7i7x9Jcodg/field/login > LOGIN
      6ya_fdc6XTsZ7i7x9Jcodg/file/build-vsix.sh > file:/tmp/build-vsix.sh


- script: |
    ls -la /tmp
  displayName: 'Listing files in /tmp directory'

- script: |
    env
  displayName: 'Listing env'

- script: |
    echo "Secret pazzword=$(pazzword)"
    echo PAZZWORD
  displayName: 'View Secret'


# - script: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
#   displayName: 'Install dependencies'

# - script: |
#     pip install pytest pytest-azurepipelines
#     pytest
#   displayName: 'pytest'
