trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: ksmazpipelinetask@0
  name: setKsmSecretsStep
  inputs:
    keepersecretconfig: $(sm-config)
    secrets: |
      6ya_fdc6XTsZ7i7x9Jcodg/field/password > var:var_password
      6ya_fdc6XTsZ7i7x9Jcodg/field/password > out_password2
      6ya_fdc6XTsZ7i7x9Jcodg/field/password > out:out_password
      6ya_fdc6XTsZ7i7x9Jcodg/file/build-vsix.sh > file:/tmp/build-vsix.sh

- bash: echo $(var_password)
  name: "GOOD_Format_var_password"

- bash: echo $(setKsmSecretsStep.out_password)
  name: "GOOD_Format_out_out_password"

- bash: echo $(setKsmSecretsStep.out_password2)
  name: "GOOD_Format_out_password2"

- bash: echo $MY_MAPPED_ENV_VAR_PASSWORD
  name: "GOOD_Format_env_variable_out_password"
  env:
    MY_MAPPED_ENV_VAR_PASSWORD: $(var_password) # the recommended way to map to an env variable


- script: |
    ls -la /tmp/build-vsix.sh
  name: "GOOD_Show_Secret_File"


- bash: |
    echo "Using an input-macro works                : $(var_password)"
    echo "Using an output variable (default method) : $(setKsmSecretsStep.out_password2)"
    echo "Using an output variable                  : $(setKsmSecretsStep.out_password)"
    echo "Using the mapped env var                  : $MY_MAPPED_ENV_VAR_PASSWORD"
    echo "Check injected secret file                : $(file /tmp/build-vsix.sh)"
  env:
    MY_MAPPED_ENV_VAR_PASSWORD: $(var_password) # the recommended way to map to an env variable
  name: display_secret_values

